#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
WORKDIR=$(mktemp -d /tmp/sudo-awesome-jwt-test.XXXXXX)
SUDO_CONF=/etc/sudo.conf
SUDO_CONF_BACKUP="$WORKDIR/sudo.conf.bak"
CONFIG_FILE="$WORKDIR/sudo_awesome_jwt.conf"
TOKEN_FILE="$WORKDIR/token.jwt"
KEY_PRIV="$WORKDIR/jwt.key"
KEY_PUB="$WORKDIR/jwt.pub"

PLUGIN_LIB=${SUDO_AWESOME_JWT_PLUGIN_LIB:-"$ROOT_DIR/sudo_awesome_jwt.so"}
TEST_CMD=${SUDO_AWESOME_JWT_TEST_COMMAND:-"/usr/bin/id"}
WAIT_SECS=${SUDO_AWESOME_JWT_TEST_WAIT:-70}
TTL_SECS=${SUDO_AWESOME_JWT_TEST_TTL:-5}
INTERACTIVE=${SUDO_AWESOME_JWT_TEST_INTERACTIVE:-0}

log() {
    echo "[test] $*"
}

write_sudo_conf_base() {
    local mode="$1"
    local dest="$2"
    if [[ -f "$SUDO_CONF_BACKUP" ]]; then
        awk -v mode="$mode" '
            $1 == "Plugin" {
                if (mode == "approval" && $2 == "approval") {
                    next
                }
                if (mode == "policy" && ($2 == "sudoers_policy" || $2 == "policy")) {
                    next
                }
            }
            { print }
        ' "$SUDO_CONF_BACKUP" > "$dest"
    else
        : > "$dest"
    fi
}

run_sudo() {
    if [[ "$INTERACTIVE" == "1" ]]; then
        sudo "$@"
    else
        sudo -n "$@"
    fi
}

run_privileged() {
    if [[ "$(id -u)" -eq 0 ]]; then
        "$@"
    else
        run_sudo "$@"
    fi
}

cleanup() {
    if [[ -f "$SUDO_CONF_BACKUP" ]]; then
        run_privileged cp "$SUDO_CONF_BACKUP" "$SUDO_CONF"
    else
        run_privileged rm -f "$SUDO_CONF"
    fi
    rm -rf "$WORKDIR"
}
trap cleanup EXIT

if ! command -v sudo >/dev/null; then
    echo "sudo not found" >&2
    exit 1
fi

if ! command -v openssl >/dev/null; then
    echo "openssl not found" >&2
    exit 1
fi

if ! command -v python3 >/dev/null; then
    echo "python3 not found" >&2
    exit 1
fi

if [[ "$(id -u)" -ne 0 ]]; then
    echo "run this test as root (e.g. sudo -E $0) to ensure sudo.conf can be restored after expiry" >&2
    exit 1
fi

if [[ ! -f "$PLUGIN_LIB" ]]; then
    log "plugin not found, building it"
    if [[ "$PLUGIN_LIB" == *"libsudo_awesome_jwt_rust.so"* ]]; then
        (cd "$ROOT_DIR/rust" && cargo build --release)
    else
        (cd "$ROOT_DIR" && make)
    fi
fi

if [[ ! -f "$PLUGIN_LIB" ]]; then
    echo "plugin library not found: $PLUGIN_LIB" >&2
    exit 1
fi

if [[ -f "$SUDO_CONF" ]]; then
    log "backing up sudo.conf"
    run_privileged cp "$SUDO_CONF" "$SUDO_CONF_BACKUP"
fi

log "generating RSA keypair"
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$KEY_PRIV" >/dev/null 2>&1
openssl rsa -in "$KEY_PRIV" -pubout -out "$KEY_PUB" >/dev/null 2>&1

log "writing test config"
cat > "$CONFIG_FILE" <<'EOF_CONFIG'
# autogenerated test config
token_file = TOKEN_FILE_PLACEHOLDER
public_key = KEY_PUB_PLACEHOLDER
issuer = "test-issuer"
audience = "test-audience"
scope = "sudo"
require_tty = false
max_ttl = 30
EOF_CONFIG

sed -i "s|TOKEN_FILE_PLACEHOLDER|$TOKEN_FILE|" "$CONFIG_FILE"
sed -i "s|KEY_PUB_PLACEHOLDER|$KEY_PUB|" "$CONFIG_FILE"

make_jwt() {
    local ttl="$1"
    log "generating JWT (ttl=${ttl}s)"
    KEY_PRIV="$KEY_PRIV" TTL_SECS="$ttl" python3 - <<'PY'
import base64
import json
import os
import subprocess
import time

key = os.environ["KEY_PRIV"]
ttl = int(os.environ["TTL_SECS"])
now = int(time.time())
header = {"alg": "RS256", "typ": "JWT"}
payload = {
    "iss": "test-issuer",
    "aud": "test-audience",
    "scope": "sudo",
    "iat": now,
    "exp": now + ttl,
}

def b64url(data: bytes) -> bytes:
    return base64.urlsafe_b64encode(data).rstrip(b"=")

signing_input = b".".join([
    b64url(json.dumps(header, separators=(",", ":")).encode()),
    b64url(json.dumps(payload, separators=(",", ":")).encode()),
])

sig = subprocess.check_output([
    "openssl", "dgst", "-sha256", "-sign", key
], input=signing_input)

jwt = b".".join([signing_input, b64url(sig)])
print(jwt.decode())
PY
}

write_token() {
    local ttl="$1"
    local token
    token=$(make_jwt "$ttl")
    log "writing token to $TOKEN_FILE"
    printf '%s' "$token" > "$TOKEN_FILE"
    chmod 600 "$TOKEN_FILE"
}

set_sudo_conf_approval() {
    log "configuring sudo.conf for approval plugin"
    write_sudo_conf_base approval "$WORKDIR/sudo.conf"
    cat >> "$WORKDIR/sudo.conf" <<'EOF_SUDO_APPROVAL'
Plugin approval PLUGIN_PATH_PLACEHOLDER config=CONFIG_PATH_PLACEHOLDER
EOF_SUDO_APPROVAL
    sed -i "s|PLUGIN_PATH_PLACEHOLDER|$PLUGIN_LIB|" "$WORKDIR/sudo.conf"
    sed -i "s|CONFIG_PATH_PLACEHOLDER|$CONFIG_FILE|" "$WORKDIR/sudo.conf"
    run_privileged cp "$WORKDIR/sudo.conf" "$SUDO_CONF"
}

set_sudo_conf_policy() {
    log "configuring sudo.conf for policy plugin"
    write_sudo_conf_base policy "$WORKDIR/sudo.conf"
    cat >> "$WORKDIR/sudo.conf" <<'EOF_SUDO_POLICY'
Plugin policy PLUGIN_PATH_PLACEHOLDER config=CONFIG_PATH_PLACEHOLDER
EOF_SUDO_POLICY
    sed -i "s|PLUGIN_PATH_PLACEHOLDER|$PLUGIN_LIB|" "$WORKDIR/sudo.conf"
    sed -i "s|CONFIG_PATH_PLACEHOLDER|$CONFIG_FILE|" "$WORKDIR/sudo.conf"
    run_privileged cp "$WORKDIR/sudo.conf" "$SUDO_CONF"
}

run_once() {
    local plugin_type="$1"
    log "testing $plugin_type plugin"

    if [[ "$plugin_type" == "approval" ]]; then
        set_sudo_conf_approval
    else
        set_sudo_conf_policy
    fi

    write_token "$TTL_SECS"
    log "running sudo command with fresh token"
    if ! output=$(run_sudo "$TEST_CMD" 2>&1); then
        echo "$output" >&2
        echo "expected sudo to succeed for $plugin_type with fresh token" >&2
        exit 1
    fi

    log "waiting $WAIT_SECS seconds for token expiry"
    sleep "$WAIT_SECS"

    log "running sudo command after expiry"
    if output=$(run_sudo "$TEST_CMD" 2>&1); then
        echo "$output" >&2
        echo "expected sudo to fail for $plugin_type after token expiry" >&2
        exit 1
    fi
}

run_once approval
run_once policy

log "all plugin tests passed"
